### ISSUE TITLE
Floating problems

### ISSUE THREAD

**Issue by Sobak** [Sobak/bugsnet-redesign-mockup#1]
`.controls` for `.bug-header` are floated to the right what affects elements below them.

![image](https://cloud.githubusercontent.com/assets/1347533/22142690/81207d04-def7-11e6-84ab-b70734a66aa2.png)

Same problem occurs with the table containing bug details what can be seen when the screen is smaller:
![image](https://cloud.githubusercontent.com/assets/1347533/22142738/ae8ae608-def7-11e6-8f14-faf2f81b842d.png)

It's probably just a matter of proper `.clearfix` but I couldn't find the right way. @dragoonis, mind looking at this when you'll have a moment?

**Comment by dragoonis** [comment]
Can you open a PR with what you have so far. Mark it as WIP. Then i can pull down your branch and look at it for you.

**Comment by Sobak** [comment]
Use code from this repo, please. It's just a mockup but it has all required CSS/HTML, not just screenshots. I didn't start implementation on php/web-bugs yet.

**Comment by soanvig** [comment]
Just do 
```CSS
#report::before {
    content: '';
    display: block;
    clear: both;
}
```
~~But this way margins doesn't overlap, so You need to remove one. I suggest removing h1 bottom margin.~~
I've just mislooked ;p
